name: circular_code_app_extended
description: Flutter app to decode custom circular codes (local Dart + optional backend HTTP).
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  image: ^4.1.3
  http: ^1.2.2
  path: ^1.9.0
  camera: ^0.11.2+1

flutter:
  uses-material-design: true
